<a href="https://colab.research.google.com/github/Geethanjaliramesh/deep-learning-learning-lab/blob/main/01_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

print("PyTorch version:", torch.__version__)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

PyTorch version: 2.11.0+cpu
Device: cpu


In [2]:
scalar = torch.tensor(7)

vector = torch.tensor([1, 2, 3])

matrix = torch.tensor([
    [1, 2],
    [3, 4]
])

tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Scalar:", scalar.shape)
print("Vector:", vector.shape)
print("Matrix:", matrix.shape)
print("3D Tensor:", tensor_3d.shape)

Scalar: torch.Size([])
Vector: torch.Size([3])
Matrix: torch.Size([2, 2])
3D Tensor: torch.Size([2, 2, 2])


In [3]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Dot product:", torch.dot(a, b))

Addition: tensor([5., 7., 9.])
Multiplication: tensor([ 4., 10., 18.])
Dot product: tensor(32.)


In [5]:
A = torch.tensor([
    [1.0, 2.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])

C = torch.matmul(A, B)

print(C)

tensor([[19., 22.]])


In [5]:
import torch
#input
x =torch.tensor([2.0,3.0])

#weights
w = torch.tensor([0.5,0.8])

#bais
b = torch.tensor(1.0)

print("input:", x)
print("weight:", w)
print("bias", b)



input: tensor([2., 3.])
weight: tensor([0.5000, 0.8000])
bias tensor(1.)


In [12]:
#multi line code
weighted_input = x * w

print(weighted_input)

weighted_sum = weighted_input.sum()
print(weighted_sum)

output = weighted_sum + b
print(output)

tensor([1.0000, 2.4000])
tensor(3.4000)
tensor(4.4000)


In [14]:
#single line code for neuron output

output = torch.dot(x,w) + b
print(output)

tensor(4.4000)


In [19]:
import torch.nn as nn
layer = nn.Linear(2, 8)
x = torch.tensor([2.0, 3.0])
output = layer(x)

print(output)

tensor([ 1.0338, -3.1562, -1.1637,  2.8568,  1.4128, -2.4969,  2.2892, -0.4514],
       grad_fn=<ViewBackward0>)


In [23]:
layer.weight.shape
layer.bias.shape


torch.Size([8])