<a href="https://colab.research.google.com/github/Geethanjaliramesh/deep-learning-learning-lab/blob/main/Sample_neuralnetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn

x = torch.tensor([
    [0.0,0.0],
    [0.0,1.0],
    [1.0,0.0],
    [1.0,1.0],
])

y = torch.tensor([
    [0.0],
    [1.0],
    [1.0],
    [1.0]
])

print("x shape",x.shape)
print("y shape",y.shape)

x shape torch.Size([4, 2])
y shape torch.Size([4, 1])


In [4]:
model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [6]:
output = model(x)
print(output)

tensor([[-0.1402],
        [-0.0581],
        [-0.2262],
        [-0.1416]], grad_fn=<AddmmBackward0>)


In [7]:
loss_function = nn.BCEWithLogitsLoss()
output = model(x)
loss = loss_function(output,y)
print(loss)

tensor(0.7318, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [8]:
loss.backward

<bound method Tensor.backward of tensor(0.7318, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)>

In [9]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.1)
optimizer.step()

optimizer.zero_grad()

In [11]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.1)

for epoch in range(1000):
  optimizer.zero_grad()

  output = model(x)

  loss = loss_function(output,y)

  loss.backward()

  optimizer.step()

  if epoch % 100 == 0:
    print(f"Epoch {epoch}, loss : {loss.item():.4f}")

Epoch 0, loss : 0.7318
Epoch 100, loss : 0.4567
Epoch 200, loss : 0.3444
Epoch 300, loss : 0.1743
Epoch 400, loss : 0.1000
Epoch 500, loss : 0.0658
Epoch 600, loss : 0.0476
Epoch 700, loss : 0.0368
Epoch 800, loss : 0.0298
Epoch 900, loss : 0.0249


In [13]:
with torch.no_grad():
  raw_outputs = model(x)
  probabilities = torch.sigmoid(raw_outputs)
  predictions = (probabilities >= 0.5).float()

print("Inputs:")
print(x)

print("\nProbabilities:")
print(probabilities)

print("\nPredictions:")
print(predictions)

print("\nCorrect answers:")
print(y)


Inputs:
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

Probabilities:
tensor([[0.0708],
        [0.9952],
        [0.9934],
        [1.0000]])

Predictions:
tensor([[0.],
        [1.],
        [1.],
        [1.]])

Correct answers:
tensor([[0.],
        [1.],
        [1.],
        [1.]])
