<a href="https://colab.research.google.com/github/Geethanjaliramesh/deep-learning-learning-lab/blob/main/Sample_P_Dataset_Dataloder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn


In [ ]:
x = torch.tensor([
    [0.0,0.0],
    [0.0,1.0],
    [1.0,0.0],
    [1.0,1.0]

])

y = torch.tensor([
    [0.0],
    [1.0],
    [1.0],
    [1.0]
])

dataset = TensorDataset(x,y)

dataloader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

for batch_x, batch_y in dataloader:

    print("Inputs:")
    print(batch_x)

    print("Labels:")
    print(batch_y)

    print("------")

for batch_x, batch_y in dataloader:

    print("X:", batch_x)
    print("y:", batch_y)

    print("X shape:", batch_x.shape)
    print("y shape:", batch_y.shape)

    print("------")

Inputs:
tensor([[1., 1.],
        [0., 0.]])
Labels:
tensor([[1.],
        [0.]])
------
Inputs:
tensor([[0., 1.],
        [1., 0.]])
Labels:
tensor([[1.],
        [1.]])
------
X: tensor([[0., 0.],
        [1., 0.]])
y: tensor([[0.],
        [1.]])
X shape: torch.Size([2, 2])
y shape: torch.Size([2, 1])
------
X: tensor([[0., 1.],
        [1., 1.]])
y: tensor([[1.],
        [1.]])
X shape: torch.Size([2, 2])
y shape: torch.Size([2, 1])
------


In [ ]:
model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

lossfunction = nn.BCEWithLogitsLoss()

optimizer = torch.optim.SGD(model.parameters(),lr=0.1)

In [ ]:

for epoch in range(1000):
    epoch_loss = 0
    for batch_X, batch_y in dataloader:

        optimizer.zero_grad()

        output = model(batch_X)

        loss = lossfunction(output, batch_y)

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()
        average_loss = epoch_loss / len(dataloader)

    if epoch % 100 == 0:
        print(f"Epoch {epoch},average {average_loss},Loss: {loss.item():.4f}")


Epoch 0,average 0.0003190607385477051,Loss: 0.0004
Epoch 100,average 0.0003095945648965426,Loss: 0.0001
Epoch 200,average 0.00030071597939240746,Loss: 0.0001
Epoch 300,average 0.00029228093626443297,Loss: 0.0002
Epoch 400,average 0.0002842490721377544,Loss: 0.0003
Epoch 500,average 0.0002766507168416865,Loss: 0.0003
Epoch 600,average 0.0002694266149774194,Loss: 0.0002
Epoch 700,average 0.0002624273838591762,Loss: 0.0004
Epoch 800,average 0.00025595877377782017,Loss: 0.0002
Epoch 900,average 0.0002497086170478724,Loss: 0.0003


In [ ]:
with torch.no_grad():

    # Get raw model outputs
    raw_outputs = model(x)

    # Convert raw outputs into probabilities
    probabilities = torch.sigmoid(raw_outputs)

    # Convert probabilities into 0 or 1
    predictions = (probabilities >= 0.5).float()

    # Check which predictions are correct
    correct = (predictions == y).sum().item()

    # Calculate accuracy
    accuracy = correct / len(y) * 100


print("Probabilities:")
print(probabilities)

print("\nPredictions:")
print(predictions)

print("\nCorrect answers:")
print(y)

print(f"\nAccuracy: {accuracy:.2f}%")

Probabilities:
tensor([[5.8761e-04],
        [9.9980e-01],
        [9.9981e-01],
        [1.0000e+00]])

Predictions:
tensor([[0.],
        [1.],
        [1.],
        [1.]])

Correct answers:
tensor([[0.],
        [1.],
        [1.],
        [1.]])

Accuracy: 100.00%
